name: chat_app
description: A new Flutter project.
publish_to: "none"
version: 9.0.0+10
# Change this package on 19/10/2023 @10:25  AM
# upload this package 26/10/2023 @17:55 PM
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.9.1
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.6
  custom_navigation_bar: ^0.8.2
  device_info_plus: ^9.0.3
  dio: ^5.3.2
  emoji_picker_flutter: ^1.6.1
  file_picker: ^8.0.6
  file_utils: ^1.0.1
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  #  flutter_local_notifications: ^15.1.1
  flutter_local_notifications: ^17.2.3
  flutter_sound: ^9.2.13
  flutter_windowmanager: ^0.2.0
  gallery_saver: ^2.3.2
  get: ^4.6.5
  hidable: ^1.0.5
  http: ^0.13.6
  image_picker: ^1.0.4
  just_audio: ^0.9.34
  line_icons: ^2.0.3
  open_filex: ^4.3.2
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  photo_view: ^0.14.0
  provider: ^6.0.5
  # record_mp3: ^3.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  sizer: ^2.0.15
  vibration: ^1.8.1
  video_player: ^2.7.1
  video_thumbnail: ^0.5.3
  zego_uikit_prebuilt_call: ^4.15.13
  zego_uikit_signaling_plugin: ^2.7.0
  firebase_core_desktop: ^1.0.2
  firebase_dart: ^1.0.11
  intl: ^0.18.1
  zego_zpns: any
  awesome_notifications: ^0.8.2
  audioplayers: ^6.0.0
  camera: ^0.10.5+5
  zego_uikit: ^2.14.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
