// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2kvO_IT_T21oSHDG-Nn8raeNShFbg2XM',
    appId: '1:351287063170:web:efe174c4bb3fe0f9807a9b',
    messagingSenderId: '351287063170',
    projectId: 'chatmitra-ff572',
    authDomain: 'chatmitra-ff572.firebaseapp.com',
    storageBucket: 'chatmitra-ff572.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3wjibcZbFZ6NbuzmrzetVzCndjDUEM0o',
    appId: '1:351287063170:android:ffb8eb8cf5be9a51807a9b',
    messagingSenderId: '351287063170',
    projectId: 'chatmitra-ff572',
    storageBucket: 'chatmitra-ff572.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2kvO_IT_T21oSHDG-Nn8raeNShFbg2XM',
    appId: '1:351287063170:web:6f418a107977fce0807a9b',
    messagingSenderId: '351287063170',
    projectId: 'chatmitra-ff572',
    authDomain: 'chatmitra-ff572.firebaseapp.com',
    storageBucket: 'chatmitra-ff572.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyD2kvO_IT_T21oSHDG-Nn8raeNShFbg2XM',
    appId: '1:351287063170:web:3696c49eec9ca178807a9b',
    messagingSenderId: '351287063170',
    projectId: 'chatmitra-ff572',
    authDomain: 'chatmitra-ff572.firebaseapp.com',
    storageBucket: 'chatmitra-ff572.appspot.com',
  );
}
